---
title: "Data analysis of chemical data"
author: "Muhammad"
date: "08/10/22"
---
# Load the required packages
```{r}
library(rcompanion)
library(readxl)# This package is useful for data import.
library(tidyverse)# package collection namely: {dplyr-} for data wrangling, {tibble-} for dataframes

# Packages for data analysis.
 library(lmerTest)
library(stats) 

```

```{r Analysis of Diclofenac(single compound:raw data), Table \@ref(tab:Anova-table}
# Import the raw data for Diclofenac.
Dfs <- read_excel(file.choose(), sheet = "Diclofenac-raw")

# List the first ten entries.
head(Dfs)

# Subset the variables
Genotype <- Dfs[, "Genotype"]
Treatment <- Dfs[, "Treatment"]
DAY <- Dfs[, "DAY"]

# create the  linear model
Dfs_lme <- lmer(concentration ~ Treatment*Genotype*DAY +(1|Genotype:Replicates), data = Dfs)

# Run Anova
anova(Dfs_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Dfs_lme)
plotNormalHistogram(x)

qqnorm(residuals(Dfs_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Dfs_lme),
       col='red')
plot(fitted(Dfs_lme),
     residuals(Dfs_lme))

# Tidy the anova summary
tidy_DicSin_raw <- tidy(Dfs_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_DicSin_raw,'Diclofenac_SIngle_raw.csv') 
```

```{r Analysis of Diclofenac removal efficiency(single compound), Table \@ref(tab:Anova-table}
# Import the data
Df_reff_Single <- read_excel(file.choose(), sheet = "Dic_reff_single")

# List the first ten entries.
head(Df_reff_Single)

# Subset the variables
Genotype <- Df_reff_Single[, "Genotype"]
Day <- Df_reff_Single[, "Day"]

# Create the  linear model
Dfrem_lme <- lmer(RE ~ Genotype*Day + (1|Genotype:Replicates), data = Df_reff_Single)

# Anova
anova(Dfrem_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Dfrem_lme)
plotNormalHistogram(x)

qqnorm(residuals(Dfrem_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Dfrem_lme),
       col='red')
plot(fitted(Dfrem_lme),
     residuals(Dfrem_lme))

# Tidy the anova summary
tidy_Dic_reff_Sin_raw <- tidy(Dfrem_lme) 

# Export the  tidied anova summary as a csv file.
write.csv(tidy_Dic_reff_Sin_raw,'Dic_reff_SIngle_raw.csv') 
```

```{r Analysis of Diclofenac(wastewater:raw data), Table \@ref(tab:Anova-table}
# Import the data
Dfw_raw <- read_excel(file.choose(), sheet = "Dic_raw_ww")

# List the first ten entries.
head(Dfw_raw)

# Subset the variables.
GENOTYPE <- Dfw_raw[, "GENOTYPE"]
TREATMENT <- Dfw_raw[, "TREATMENT"]
DAY <- Dfw_raw[, "DAY"]

# create the linear model.
Dfw_lme <- lmer(concentration ~ TREATMENT*GENOTYPE*DAY +(1|GENOTYPE:Replicates), data = Dfw_raw)

# Anova
anova(Dfw_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Dfw_lme)
plotNormalHistogram(x)

qqnorm(residuals(Dfw_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Dfw_lme),
       col='red')
plot(fitted(Dfw_lme),
     residuals(Dfw_lme))

# Tidy the anova summary.
tidy_Dic_ww_raw <- tidy(Dfw_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_Dic_ww_raw,'Diclofenac_ww_raw.csv') 
```

```{r Analysis of Diclofenac removal efficiency (wastewater), Table \@ref(tab:Anova-table}
# Import the data.
DfwW_reff <- read_excel(file.choose(), sheet = "Dic-ww-reff")

# list the first ten entries.
head(DfwW_reff)

# Subset the variables.
Genotype <- DfwW_reff[, "Genotype"]
Day <- DfwW_reff[, "Day"]

# create the linear model.
Df_ww_rem_lme <- lmer(RE ~ Genotype*Day + (1|Genotype:Replicates), data = DfwW_reff)

# Anova 
anova(Df_ww_rem_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Df_ww_rem_lme)
plotNormalHistogram(x)

qqnorm(residuals(Df_ww_rem_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Df_ww_rem_lme),
       col='red')
plot(fitted(Df_ww_rem_lme),
     residuals(Df_ww_rem_lme))

# Tidy the anova summary.
tidy_Dic_ww_reff <- tidy(Df_ww_rem_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_Dic_ww_reff,'Dic_reff_ww.csv') 
```

```{r Analysis of PFOS(single compound:raw data, Table \@ref(tab:Anova-table}
# Import the data.
Pfs <- read_excel(file.choose(), sheet = "Pfos_raw")

# List the first ten entries.
head(Pfs)

# Subset the variables.
Genotype <- Pfs[, "Genotype"]
Treatment <- Pfs[, "Treatment"]
DAY <- Pfs[, "DAY"]

# Create the linear model
Pfs_lme <- lmer(concentration ~ Treatment*Genotype*DAY +(1|Genotype:Replicates), data = Pfs)

# Anova
anova(Pfs_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Pfs_lme)
plotNormalHistogram(x)

qqnorm(residuals(Pfs_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Pfs_lme),
       col='red')
plot(fitted(Pfs_lme),
     residuals(Pfs_lme))

# Tidy the anova summary.
tidy_Pfs_raw <- tidy(Pfs_lme) 

# Export the tidied anova as a csv file.
write.csv(tidy_Pfs_raw,'Pfos_sin_raw.csv') 
```

```{r Analysis of PFOS removal efficiency (single-compound), Table \@ref(tab:Anova-table}
# Import the data
Pfos_reff <- read_excel(file.choose(), sheet = "Pfos_reff-sin")

# List the first ten entries.
head(Pfos_reff)

# Subset the variables
Genotype <- Pfos_reff[, "Genotype"]
Day <- Pfos_reff[, "Day"]

# create the linear model.
Pfos_sin_rem_lme <- lmer(RE ~ Genotype*Day + (1|Genotype:Replicates), data = Pfos_reff)

# anova
anova(Pfos_sin_rem_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Pfos_sin_rem_lme)
plotNormalHistogram(x)

qqnorm(residuals(Pfos_sin_rem_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Pfos_sin_rem_lme),
       col='red')
plot(fitted(Pfos_sin_rem_lme),
     residuals(Pfos_sin_rem_lme))

# Tidy the anova summary.
tidy_Pfos_sin_reff <- tidy(Pfos_sin_rem_lme) 

# Export the anova summary as a csv file.
write.csv(tidy_Pfos_sin_reff,'Pfos_reff_sin.csv') 
```

```{r Analysis of PFOS(wastewater:raw data,Table \@ref(tab:Anova-table}
# Import the data
Pfos_ww <- read_excel(file.choose(), sheet = "Pfos_raw_ww")

# List the first ten entries.
head(Pfos_ww)

# Subset the variables.
Genotype <- Pfos_ww[, "Genotype"]
Treatment <- Pfos_ww[, "Treatment"]
DAY <- Pfs[, "DAY"]

# Create the linear model.
Pfos_ww_lme <- lmer(Concentration ~ Treatment*Genotype*DAY +(1|Genotype:Replicates), data = Pfos_ww)

# Anova.
anova(Pfos_ww_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Pfos_ww_lme)
plotNormalHistogram(x)

qqnorm(residuals(Pfos_ww_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Pfos_ww_lme),
       col='red')
plot(fitted(Pfos_ww_lme),
     residuals(Pfos_ww_lme))

# Tidy the anova summary.
tidy_Pfos_ww_raw <- tidy(Pfos_ww_lme) 

# Export the anova summary as a csv file.
write.csv(tidy_Pfos_ww_raw,'Pfos_ww_raw.csv') 
```

```{r Analysis of PFOS removal efficiency (wastewater), Table \@ref(tab:Anova-table}
# Import the data
Pfos_ww <- read_excel(file.choose(), sheet = "Pfos_ww_reff")

# List the first ten entries.
head(Pfos_ww)

# Subset the variables.
Genotype <- Pfos_ww[, "Genotype"]
Day <- Pfos_ww[, "Day"]

# Create the linear model.
Pfos_ww_reff_lme <- lmer(RE ~ Genotype*Day + (1|Genotype:Replicates), data = Pfos_ww)

# Anova.
anova(Pfos_ww_reff_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Pfos_ww_reff_lme)
plotNormalHistogram(x)

qqnorm(residuals(Pfos_ww_reff_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Pfos_ww_reff_lme),
       col='red')
plot(fitted(Pfos_ww_reff_lme),
     residuals(Dfrem_lme))

# tidy the anova summary.
tidy_Pfos_ww_reff <- tidy(Pfos_ww_rem_lme) 

# Export the anova summary as a csv file.
write.csv(tidy_Pfos_ww_reff,'Pfos_reff_ww.csv') 
```

```{r Analysis of Arsenic (raw), Table \@ref(tab:Anova-table}
# Import the data
Ars <- read_excel(file.choose(), sheet = "Arsenic-raw")

# List the first ten entries.
head(Ars)

# Subset the variables.
Genotype <- Ars[, "Genotype"]
Treatment <- Ars[, "Treatment"]
DAY <- Ars[, "DAY"]

# Create the linear model.
Ars_lme <- lmer(Concentration ~ Treatment*Genotype*DAY +(1|Genotype:Replicates), data = Ars)

# Anova
anova(Ars_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Ars_lme)
plotNormalHistogram(x)

qqnorm(residuals(Ars_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Ars_lme),
       col='red')
plot(fitted(Ars_lme),
     residuals(Ars_lme))

# tidy the anova summary.
tidy_Ars <- tidy(Ars_lme)

# Export the tidied anova summary as a csv file.
write.csv(tidy_Ars,'Ars.csv') 
```

```{r Analysis of Arsenic uptake, Table \@ref(tab:Anova-table}
Ars_upt <- read_excel(file.choose(), sheet = "Arsenic-uptake")

# List the first ten entries.
head(Ars_upt)

# Subset the variables.
Genotype <- Ars_upt[, "Genotype"]
Treatment <- Ars_upt[, "Treatment"]
DAY <- Ars_upt[, "DAY"]

# create the linear model.
Ars_upt_lme <- lmer(concentration ~ Treatment*Genotype*DAY +(1|Genotype:Replicates), data = Ars_upt)

# Anova.
anova(Ars_upt_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Ars_upt_lme)
plotNormalHistogram(x)

qqnorm(residuals(Ars_upt_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Ars_upt_lme),
       col='red')
plot(fitted(Ars_upt_lme),
     residuals(Ars_upt_lme))

# Tidy the anova summary.
tidy_Ars_upt <- tidy(Ars_upt_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_Ars_upt,'Ars_upt.csv') 
```

```{r Analysis of Arsenic removal efficiency, Table \@ref(tab:Anova-table}
# Import the data
Ars_rem <- read_excel(file.choose(), sheet = "Arsenic-reff")

# List the first ten entries.
head(Ars_rem)

# Subset the variables.
Genotype <- Ars_rem[, "Genotype"]
Day <- Ars_rem[, "Day"]

# Create the linear model.
Ars_reff_lme <- lmer(RE ~ Genotype*Day + (1|Genotype:Replicates), data = Ars_rem)

# Anova.
anova(Ars_reff_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Ars_reff_lme)
plotNormalHistogram(x)

qqnorm(residuals(Ars_reff_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Ars_reff_lme),
       col='red')
plot(fitted(Ars_reff_lme),
     residuals(Ars_reff_lme))

# Tidy the anova summary.
tidy_Ars_reff <- tidy(Ars_reff_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_Ars_reff,'Ars_reff.csv') 
```

```{r Analysis of Atrazine raw data, Table \@ref(tab:Anova-table}
# Import the data.
Atr_raw <- read_excel(file.choose(), sheet = "Atrazine_raw")

# list the first ten entries.
head(Atr_raw)

# Subset the variables.
Genotype <- Atr_raw[, "Genotype"]
Treatment <- Atr_raw[, "Treatment"]
DAY <- Atr_raw[, "DAY"]

# Create the linear model.
Atr_lme <- lmer(Concentration ~ Treatment*Genotype*DAY +(1|Genotype:Replicates), data = Atr_raw)

# Anova
anova(Atr_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Atr_lme)
plotNormalHistogram(x)

qqnorm(residuals(Atr_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Atr_lme),
       col='red')
plot(fitted(Atr_lme),
     residuals(Atr_lme))

# Tidy the anova summary.
tidy_Atr <- tidy(Atr_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_Atr,'Atrazine_raw.csv') 
```

```{r Analysis of Atrazine removal efficiency,Table \@ref(tab:Anova-table}
# Import the data
atr_rem <- read_excel(file.choose(), sheet = "Atrazine-reff")

# List the first ten entries
head(atr_rem)

# Subset the variables.
Genotype <- atr_rem[, "Genotype"]
Day <- atr_rem[, "Day"]

# Create the linear model.
Atr_reff_lme <- lmer(RE ~ Genotype*Day + (1|Genotype:Replicates), data = Atr_rem)

# Anova.
anova(Atr_reff_lme) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(Atr_reff_lme)
plotNormalHistogram(x)

qqnorm(residuals(Atr_reff_lme),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(Atr_reff_lme),
       col='red')
plot(fitted(Atr_reff_lme),
     residuals(Atr_reff_lme))

# Tidy the anova summary.
tidy_Atr_reff <- tidy(Atr_reff_lme) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_Atr_reff,'Atr_reff.csv') 
```

```{r Analysis of variance-Prototype (Diclofenac (single compound), Table \@ref(tab:Anova-table}
#import the raw data:
mesocosm <-read_excel(file.choose(), sheet = 'Prototype_raw')

# list the first ten entries.
head(mesocosm)

# subset the variables:
Day<-mesocosm[,'Day']
Genotype<- mesocosm[,'Genotype']
Treatment<- mesocom[,'Treatment']

# Create the linear model.
meso_ano<-lmer(Concentration~Treatment*DAY*Genotype+(1|Genotype:Replicates),data = mesocosm)

# Anova.
anova(meso_ano) 

#check for homogeneity of variance and heteroscedacity:
x=residuals(meso_ano)
plotNormalHistogram(x)

qqnorm(residuals(meso_ano),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(meso_ano),
       col='red')
plot(fitted(meso_ano),
     residuals(meso_ano))

# Tidy the anova summary.
tidy_meso <- tidy(meso_ano) 

# Export the tidied anova summary as a csv file.
write.csv(tidy_meso,'meso_raw.csv') 
```

```{r Analysis of variance-Prototype(Diclofenac (removal efficiency), Table \@ref(tab:Anova-tabl}
# Import the data
mesRE<-read_excel(file.choose(), sheet = 'removal-effic')

# List the first ten entries.
head(mesRE)

# Subset the variables
Day <- mesRE[, "Day"]
Genotype <- mesRE[, "Genotype"]

# Create the linear model.
mes_re <- lmer(RE~Genotype*Day +(1|Genotype:Replicates),
             data = mesRE)

# Anova.
anova(mes_re)

#check for homogeneity of variance and heteroscedacity:
x=residuals(meso_re)
plotNormalHistogram(x)

qqnorm(residuals(meso_re),
       ylab = 'Sample Quantiles for residuals')
qqline(residuals(meso_re),
       col='red')
plot(fitted(meso_re),
     residuals(meso_re))

# Tidy the anova summary.
tidy_meso_re <- tidy(meso_re) 

# Export the anova summary as a csv file.
write.csv(tidy_meso_re,'meso_reff.csv') 
```

