---
title: "Data analysis of chemical data"
author: "Muhammad"
date: "08/10/22"
---



# load required packages
```{r}

library(tidyverse) # package collection namely: {dplyr-} for data wrangling, {tibble-} for dataframes
library(ggplot2) # part of the {tidyverse} package collection

# Packages for interactive visualisation.
library(readxl) 
library(R2PPT)
library(RDCOMClient)

# Packages for data analysis
library(Rmisc) 
library(lmerTest)
library(stats) 

```

```{r Diclofenac-single compound, fig.cap="Concentration of Diclofenac (single compound) after exposure to Daphnia genotypes.}

# Import the data for Diclofenac (single)
DiclofenacSingle <- read_excel(file.choose(), sheet = "raw-single") 

```

```{r}
# calculate the standard error
DiclofenacSingle_SE <- summarySE(DiclofenacSingle, measurevar = "concentration", groupvars = c("Genotype", "Day"), na.rm = TRUE, .drop = TRUE)

head(DiclofenacSingle_SE)

# Make a plot of the concentration.
pd = position_dodge(0.1)

plot_DicloConc <- ggplot(
  DiclofenacSingle_SE, aes(x = Day, y = concentration, 
                        colour = Genotype, 
                        group = interaction(Genotype))) +
  geom_line(position = pd, 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = concentration-se, 
                    ymax = concentration+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Diclofenac concentration (mg/L)",
       tag = "a")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "CONTROL")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(plot_DicloConc)
```

```{rDiclofenac-single compound, fig.cap="Removal efficiency of Diclofenac (single compound) after exposure to Daphnia genotypes}

# import the data:Diclofenac removal efficiency.

DicloEfficiencySingle <- read_excel(file.choose(), sheet = "rem-single")

# calculate the standard error

DicloEfficiencySE <- summarySE(DicloEfficiencySingle, measurevar = "RE", groupvars = c("Genotype", "Day"),
                               na.rm = TRUE,
                               .drop = TRUE)

head(DicloEfficiencySE)

# Plot removal efficiency: Diclofenac single.

DicloRESingle <- ggplot(DicloEfficiencySE, aes(x = Day, y = concentration, colour = Genotype, group = interaction(Genotype))) +
  #geom_line(position = pd, 
   #         size = 1, 
    #        linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = concentration-se, 
                    ymax = concentration+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Diclofenac Removal efficiency (%)",
       tag = "b")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(DicloRESingle)

```

```{r Diclofenac-wastewater, fig.cap='Diclofenac concentration (wastewater) after exposure to Daphnia genotypes}

# import the data: Diclofenac in wastewater.

DiclofenacWW <- read_excel(file.choose(),sheet = "raw-wastewater")

# calculate the standard error:

DiclofenacWWSE <- summarySE(DiclofenacWW, measurevar = "CONCENTRATION", groupvars = c("GENOTYPE", "DAY"),
na.rm = TRUE, .drop = TRUE)

head(DiclofenacWWSE)

# Plot the concentration.

DicloConcWW <- ggplot(DiclofenacWWSE, aes(x = Day,y = CONCENTRATION, colour = GENOTYPE, group = interaction(GENOTYPE))) +
  geom_line(position = pd, 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = CONCENTRATION-se, 
                    ymax = CONCENTRATION+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Diclofenac concentration (ng/L)",
       tag = "c")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "CONTROL")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(DicloConcWW)

```

```{rDiclofenac-wastewater, fig.cap='Removal efficiency of Diclofenac (wastewater) after exposure to Daphnia genotypes}

# import the data: Diclofenac(wastewater) 
DicloREWW <- read_excel(file.choose(), sheet = "rem-wastewater")

# Standard error of the data:

DicloWWSE <- summarySE(DicloREWW, measurevar = "RE",
                       groupvars = c("Genotype", "Day"),
                       na.rm = TRUE,
                       .drop = TRUE)

head(DicloWWSE)

# Plot the graph for the concentration

DicloConcRE <- ggplot(DicloWWSE, aes(x = Day, 
    y = RE,  colour = Genotype, group = interaction(Genotype))) +
  geom_line(position = pd, 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = RE-se, 
                    ymax = RE+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Removal efficiency of Diclofenac (%)",
       tag = "d")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(DicloConcRE)

```

```{rAtrazine-compound, fig.cap='Concentration of Atrazine (single compound) after exposure to Daphnia genotypes}

# Import the data.
Atrazine <- read_excel(file.choose(), sheet = "raw-single")


# calculate the standard error:
 AtrazineSE <- summarySE(Atrazine, measurevar = "Concentration", groupvars = c("Genotype", "Day"),
                         na.rm = TRUE,
                         .drop = TRUE)
 
head(AtrazineSE)

 # Plot the concentration.
 AtrazineRaw <- ggplot(AtrazineSE, aes(x = Day, y = RE, 
              colour = Genotype, 
              group = interaction(Genotype
                                                                ))) +
  geom_line(position = pd, 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = Concentration-se, 
                    ymax = Concentration+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Atrazine concentration (mg/L)",
       tag = "e")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "control")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(AtrazineRaw)
```

```{rAtrazine-compound, fig.cap='Removal efficiency of Atrazine (single compound) after exposure to Daphnia genotypes}

# import the data:
AtrazineRE <- read_excel(file.choose(), sheet = "rem-single")

# calculate the standard error:
AtrazineRESE <- summarySE(AtrazineRE, measurevar = "RE",
                groupvars = c("Genotype", "Day"),
                na.rm = TRUE,
                .drop = TRUE)

head(AtrazineRESE)

# Plot the removal efficiency.

AtrazRE <- ggplot(AtrazineRESE, aes(x = Day, 
          y = RE, 
          colour = Genotype, 
          group = interaction(Genotype
                                                                ))) +
  #geom_line(position = pd, 
    #        size = 1, 
   #         linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = RE-se, 
                    ymax = RE+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Removal efficiency (%)",
       tag = "f")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(AtrazRE)
```

```{rArsenic-compound, fig.cap='Concentration of arsenic (single compound) after exposure to Daphnia genotypes}

# import the data:
Arsenic <- read_excel(file.choose(), sheet = "Raw-single")

# Calculate the standard error:
ArsenicSE <- summarySE(Arsenic, measurevar = "Concentration",groupvars = c("Genotype", "Day"),
              na.rm = TRUE,
              .drop = TRUE)

head(ArsenicSE)

# plot the concentration:

ArsenicCon <- ggplot(ArsenicSE, aes(x = Day, 
              y = Concentration, 
              colour = Genotype, 
              group = interaction(Genotype
                                                                ))) +
  geom_line(position = pd, 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = Concentration-se, 
                    ymax = Concentration+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Concentration of arsenic (ug/L)",
       tag = "g")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "CONTROL")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(ArsenicCon)
```

```{rArsenic-compound, fig.cap='removal efficiency of arsenic (single compound) after exposure to Daphnia genotypes}

# Import the data:
 ArsenicRE <- read_excel(file.choose(), sheet = "rem-single")

# Calculate the standard error the data
ArseniceSE <- summarySE(ArsenicRE, measurevar = "RE",
              groupvars = c("Genotype", "Day"), 
              na.rm = TRUE,
              .drop = TRUE)

head(ArsniceSE)

# Plot the removal efficiency:
ArsRE <- ggplot(ArseniceSE, aes(x = Day, 
                y = RE, 
                colour = Genotype, 
                group = interaction(Genotype
                                                                ))) +
  #geom_line(position = pd, 
   #         size = 1, 
    #        linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = RE-se, 
                    ymax = RE+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Removal efficicency of arsenic (%)",
       tag = "g")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(ArsenicCon)
```

```{rArsenic-compound, fig.cap='Uptake of arsenic (single compound) after exposure to Daphnia genotypes}

# Import the data:
arseninUptake <- read_excel(file.choose(), sheet = "uptake-raw")

# Calculate the standard error of the data:
arsenicSE <- summarySE(arseninUptake, measurevar = "concentration",groupvars = c("Genotype", "Day"),
                       na.rm = TRUE,
                       .drop = TRUE)

head(arsenicSE)

# Plot the uptake concentration:
ArsUptake <- ggplot(arsenicSE, aes(x = Day, 
             y = concentration, 
             colour = Genotype, 
             group = interaction(Genotype
                                                                ))) +
  geom_line(position = pd, 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = concentration-se, 
                    ymax = concentration+se), 
                width = .2,
                position = pd) +
  #ylim(10, 100) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Arsenic Uptake (ng/perbody mass)",
       tag = "g")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "CONTROL")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(ArsUptake)
```

```{rArsenic-compound, fig.cap='Uptake & removal of arsenic (single compound) after exposure to Daphnia genotypes}

# import the data
AUR <- read_excel(file.choose(), sheet = "Arsenic-uptake-remo")

head(AUR)

# calculate the standard error
AUR_SE <- summarySE(AUR, measurevar = "Abvalue", groupvars = c("Measurement", "Day", "Genotype"), na.rm = TRUE, .drop = TRUE)

head(AUR_SE)

# Plot the uptake and removal

upt-rem <- ggplot(AUR_SE, aes(x = Genotype,
                                       y = Abvalue,
                                       colour = Measurement)) +
  geom_point(position = pd) +
  #geom_smooth(span = .2) +
  geom_errorbar(aes(ymin = Abvalue-se,
                    ymax = Abvalue+se),
                width = .2,
                position = pd) +
   ylim(0, 4) +
  facet_wrap(~Day)+
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (Days)", 
       y = "Abvalue",
       tag = "h")+
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

print(upt_rem)
```

```{rMesocosm-Diclofenac, fig.cap='concentration of diclofenacn (Mesocosm) after exposure to two mixed Daphnia genotypes}

# import the raw data for the final concentration after exposure. 
mesoDic <- read_excel(file.choose(), sheet = "Raw_conc")

# calculate the stderror:
mesoDicSE <- summarySE(mesoDic, measurevar = "concentration",
                       groupvar = "DAY",
                       na.rm = TRUE,
                       .drop = TRUE)
head(mesoDicSE)

# plot the line graph for the raw concentration:

p_eco_conc <- ggplot(mesoDicSE, 
                     aes(x = DAY , 
                         y = concentration)) +
  geom_line(position = pd, color = "firebrick", 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd, 
             color = "firebrick") +
  geom_errorbar(aes(ymin = concentration-se, 
                    ymax = concentration+se), 
                width = .2,
                position = pd, 
                color = "firebrick") +
  #ylim(0, 100) +
  #xlim(-40.0, 26) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (DAY)", 
       y = "concentration of diclofenac (mg/l)",
       tag = "b")+
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6, 45, 6, 6),
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(p_eco_conc)
```

```{rMesocosm-Diclofenac, fig.cap='Removal efficiency of diclofenac (Mesocosm) after exposure to two mixed Daphnia genotypes}

# import the raw data for the removal efficiency
rawMeso <- read_excel(file.choose(), sheet = "removal-effic")

# calculate the stderror:
rawMesoSE <- summarySE(rawMeso, measurevar = "RE",
                       groupvar = "DAY",
                       na.rm = TRUE,
                       .drop = TRUE)

head(rawMesoSE)

# make a plot of the removal efficiency of diclofenAC :
p_eco <- ggplot(rawMesoSE, 
                aes(x = DAY , 
                    y = RE)) +
  geom_line(position = pd, color = "firebrick", 
            size = 1, 
            linetype = "twodash") +
  geom_point(position = pd, 
             color = "firebrick") +
  geom_errorbar(aes(ymin = RE-se, 
                    ymax = RE+se), width = .2,
                position = pd, 
                color = "firebrick") +
  ylim(-40.0, 100) +
  #xlim(-40.0, 26) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (WEEKS)", 
       y = "Removal efficiency (%)",
       tag = "a")+
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6, 45, 6, 6),
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))

print(p_eco)
```

```{rPFOS-concentration, fig.cap='Concentration of PFOS after exposure to Daphnia genotypes}

# import the data for pfos concentration:
pfos <- read_excel(file.chose(), sheet = "raw-single")

# calculate the stderror of the imported data:
pfosSE <- summarySE(pfos, measurevar = "concentration",
                    groupvar = c("Genotype", "DAY"),
                    na.rm = TRUE,
                    .drop = TRUE)

head(pfosSE)

# make a plot of the final concentration:
p_f <- ggplot(pfosSE, aes(x = DAY, 
                          y = concentration, 
                          colour = Genotype, 
                          group = interaction(Genotype))) +
  geom_line(position = pd, size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = concentration-se, ymax = concentration+se), 
                width = .2,
                position = pd) +
  #ylim(-10, 50) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (DAY)", 
       y = "concentration of pfos (ng/l)",
       tag = "b")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "CONTROL")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))
print(p_f)
```

```{rPFOS-concentration-wastewater, fig.cap='Concentration of PFOS after exposure to Daphnia genotypes}

# IMPORT THE DATA FOR PFOS WASTEWATER:
PFOSww <- read_excel(file.choose(), sheet = "conccentration")

# calculate the stderror of the imported data:
PFOSwwSE <- summarySE(PFOSww, measurevar = "conccentration",
                      groupvar = c("Genotype","Day"),
                      na.rm = TRUE,
                      .drop = TRUE)

head(PFOSwwSE)

# make a plot of the data:
pfw <- ggplot(PFOSwwSE, aes(x = Day, 
                          y = conccentration, 
                          colour = Genotype, 
                          group = interaction(Genotype))) +
  geom_line(position = pd, size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = conccentration-se, ymax = conccentration+se), 
                width = .2,
                position = pd) +
  #ylim(-10, 50) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (DAY)", 
       y = "concentration of pfos (ng/l)",
       tag = "b")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "control")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))
print(pfw)
```

```{rPFOS-concentration, fig.cap='removal efficiency of PFOS after exposure to Daphnia genotypes}

#import the data for removal efficiency:
pfosRE <- read_excel(file.choose(), sheet = "single-rem")

# calculate the summary statistics of the imported data:
pfosREse <- summarySE(pfosRE, measurevar = "RE", 
                      groupvar = c("Genotype", "Day"),
                      na.rm = TRUE,
                      .drop = TRUE)
head(pfosREse)

# make a plot of the data:
pfre <- ggplot(pfosREse, aes(x = Day, 
                          y = RE, 
                          colour = Genotype, 
                          group = interaction(Genotype))) +
  geom_line(position = pd, size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = RE-se, ymax = RE+se), 
                width = .2,
                position = pd) +
  #ylim(-10, 50) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (DAY)", 
       y = "Removal efficiency of PFOS (%)",
       tag = "b")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))
print(pfw)pfw <- ggplot(PFOSwwSE, aes(x = Day, 
                          y = conccentration, 
                          colour = Genotype, 
                          group = interaction(Genotype))) +
  geom_line(position = pd, size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = conccentration-se, ymax = conccentration+se), 
                width = .2,
                position = pd) +
  #ylim(-10, 50) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (DAY)", 
       y = "concentration of pfos (ng/l)",
       tag = "b")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3", "control")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))
print(pfre)
```

```{rPFOS-concentration-wastewater, fig.cap='removal efficiency of PFOS after exposure to Daphnia genotypes}

# import the data for removal efficiency in wastewater:
pfosREWW <- read_excel(file.choose(), sheet ="rem-wastewater")

# calculate a stderror & SD of the imported data:
pfosSE <- summarySE(pfosREWW, measurevar = "RE",
                    groupvar = c("Genotype","Day"),
                    na.rm = TRUE,
                    .drop = TRUE)

head(pfosSE)

# make a plot of the summarised data:
pfreWW <- ggplot(pfosSE, aes(x = Day, 
                          y = RE, 
                          colour = Genotype, 
                          group = interaction(Genotype))) +
  geom_line(position = pd, size = 1, 
            linetype = "twodash") +
  geom_point(position = pd) +
  geom_errorbar(aes(ymin = RE-se, ymax = RE+se), 
                width = .2,
                position = pd) +
  #ylim(-10, 50) +
  coord_cartesian(clip = "off") +
  theme_set(theme_bw()) +
  labs(x = "Time (DAY)", 
       y = "Removal efficiency of PFOS in wastewater (%)",
       tag = "b")+
  scale_color_discrete(
    name = "Genotype:",
    labels = c("LR2-36-1", "LRV0-1", "LRV12_3", "LRV8.5-3")
  ) +
  theme(axis.title.x = element_text(size = 15),
        panel.grid = element_blank(),
        plot.margin = margin(6,45, 6, 6),
        #legend.position = "none",
        axis.text = element_text(color = "black", size = 15),
        axis.title.y = element_text(vjust = 2, size = 15))
print(pfreWW)

```

